// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUcaNzE1qJHplu2LezLnHJ335VzS_EpuI',
    appId: '1:800333848813:web:690ccff6068a8bcd232ce4',
    messagingSenderId: '800333848813',
    projectId: 'lapor-fsm',
    authDomain: 'lapor-fsm.firebaseapp.com',
    storageBucket: 'lapor-fsm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC4Gtpvo-WJRCA23P0zJ_Mq_mZ8cEHPmU',
    appId: '1:800333848813:android:587b5a3fdac8de5d232ce4',
    messagingSenderId: '800333848813',
    projectId: 'lapor-fsm',
    storageBucket: 'lapor-fsm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7i9MyyLajb0VrUeLKJzGmShOM_Wb0zQQ',
    appId: '1:800333848813:ios:ae7deb7f3f901564232ce4',
    messagingSenderId: '800333848813',
    projectId: 'lapor-fsm',
    storageBucket: 'lapor-fsm.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );
}
